# Generated by Django 3.1.4 on 2021-01-02 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20210102_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 18, 51, 41, 550299, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
