# Generated by Django 3.1.4 on 2021-01-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20201114_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='moto',
        ),
    ]
