# Generated by Django 2.2.17 on 2020-11-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='категория товара')),
                ('description', models.TextField(blank=True, verbose_name='описание категории')),
            ],
        ),
    ]
