# Generated by Django 2.2.17 on 2020-11-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201105_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moto',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товар'},
        ),
        migrations.AlterModelOptions(
            name='motocategory',
            options={'verbose_name': 'категория товара', 'verbose_name_plural': 'категории товаров'},
        ),
        migrations.AddField(
            model_name='moto',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
    ]
